name: Deploy a Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Subir archivos a Hostinger por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: phiobusiness.es
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
